#       _                  ____                _ 
#      / \  _   _ _ __ ___|  _ \ _ __ ___   __| |
#     / _ \| | | | '__/ _ \ |_) | '__/ _ \ / _` |
#    / ___ \ |_| | | |  __/  __/| | | (_) | (_| |
#   /_/   \_\__,_|_|  \___|_|   |_|  \___/ \__,_|
#                                                 

# position of the world spawn
# world_spawn: [world_index, x, y, z]
world_spawn: [0, 110, 3, -21]

# Strings for game status
# in_game_status: <status_of_the_game_where_is_running>
in_game_status: "In game"
# waiting_status: <status_of_the_game_where_is_in_lobby>
waiting_status: "In lobby"

# list of strings
strings:
  # <MAP> : name of the map
  map_has_started: "The map '<MAP>' has started"
  # <MAP> : name of the map
  map_has_stopped: "The map '<MAP>' has stopped"
  # <MAP> : name of the map
  status_map_name: "Map name: '<MAP>'"
  # <PLAYERS> : number of players in the game
  status_players_count: "Players: <PLAYERS>"
  # <STATUS> : status of the game
  status_map_status: "Status: <STATUS>"
  you_start_your_extraction: "you start your extraction"
  you_has_extracted: "you are extracted"
  # <TIMER> : time before teleportation to the game
  you_time_before_extraction: "You have to wait <TIMER>s before extracting"
  # <TIMER> : time before teleportation to the game
  you_join_game_wait_time_tp: "You will be teleported in <TIMER>s"
  you_join_game_title_of_title: "Good game"
  you_join_game_subtitle_of_title: "Search chests, survive and extract the stuff"
  you_join_game_command: "You have joined the game"
  you_leave_game_command: "You have left the game"
  error_game_does_not_exist: "§cThis game doesn't exist"
  error_game_already_exist: "§cThis game already exist"
  error_game_is_full: "§cThis game is full"
  error_game_already_started: "§cThis game is already started"
  error_game_enough_players_to_start: "§cThere is not enough players to start the game"
  error_command_sender_is_not_player: "§cYou must be a player to execute this command"
  # <PLAYER> : name of the player who made the error
  error_player_not_in_game: "§c<PLAYER> is not in a game"
  error_you_are_not_in_game: "§cYou are not in a game"
  # <PLAYER> : name of the player who made the error
  error_player_has_quit_game: "§c<PLAYER> has quit the game"
  error_you_have_quit_game: "§cYou have quit the game"
  # <PLAYER> : name of the player who made the error
  error_player_already_in_game: "§c<PLAYER> is already in a game"
  error_you_are_already_in_game: "§cYou are already in a game"
  # <PLAYER> : name of the player who made the error
  error_player_has_extracted: "§c<PLAYER> has extracted"
  error_you_have_extracted: "§cYou have extracted"
  # <PLAYER> : name of the player who made the error
  error_player_has_died: "§c<PLAYER> has died"
  error_you_have_died: "§cYou have died"

# list of lists of chests items
# for <item_id> check all materials in https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# loots:
#   <type_name>
#     <list_name>:
#       <item_id>: <item_count>
#       <item_id>: <item_count>
#   <type_name>
#     <list_name>:
#       <item_id>: <item_count>
#       <item_id>: <item_count>
#   <type_name>
#     <list_name>:
#       <item_id>: <item_count>
#       <item_id>: <item_count>
loots:
  medical:
    list1:
      GOLDEN_APPLE: 87
  armor:
    list1:
      IRON_HELMET: 1
      IRON_CHESTPLATE: 1
      IRON_LEGGINGS: 1
      IRON_BOOTS: 1
  weapons:
    list1:
      IRON_SWORD: 1
    list2:
      IRON_PICKAXE: 1
      IRON_AXE: 1
      IRON_SHOVEL: 1
  food:
    list1:
      BEEF: 64
      APPLE: 32
    list2:
      BREAD: 64
      COOKED_BEEF: 16
      COOKED_CHICKEN: 16

# configuration of the scoreboard display
# fields remplaceable in the text
# <TIME> : time left in the game
# <PLAYERS> : number of players in the game
# <ALIVE> : number of players alive in the game
# <EXTRACTED> : number of players extracted in the game
# <KILLS> : number of kills of the player
# scoreboard:
#   title: <title_of_the_scoreboard>
#   lines:
#     - <line_1>
#     - <line_2>
#     - <line_3>
#     - <line_4>
#     - <line_5>
scoreboard:
  title: "§6§lTarkox game"
  lines:
    - "§6----------------------------"
    - "§6§lTime left: §e<TIME>"
    - "§6§lPlayers: §e<PLAYERS>"
    - "§6§lAlive: §e<ALIVE>"
    - "§6§lExtracted: §e<EXTRACTED>"
    - "§6§lKills: §e<KILLS>"

# list of game instances information
# games:
#   <map_name>:
#     world_index: <index_of_the_world>
#     name: <name_of_map>
#     duration_time: <duraction_of_game_in_seconds>
#     wait_time_before_tp: <wait_time_before_tp_in_seconds>
#     max_players_nb: <max_number_of_players>
#     wait_area_spawn: [x, y, z]
#     extraction_areas:
#       <zone_name>:
#         min: [x, y, z]
#         max: [x, y, z]
#         wait_time: <wait_time_before_exctraction_in_seconds>
#       <zone_name>:
#         min: [x, y, z]
#         max: [x, y, z]
#         wait_time: <wait_time_before_exctraction_in_seconds>
#   chests:
#     <type_name>:
#       <chest_name>: [x, y, z]
#       <chest_name>: [x, y, z]
#     <type_name>:
#       <chest_name>: [x, y, z]
#       <chest_name>: [x, y, z]
#     <type_name>:
#       <chest_name>: [x, y, z]
#       <chest_name>: [x, y, z]
#   spawns:
#     <spawn_name>: [x, y, z]
#     <spawn_name>: [x, y, z]
#     <spawn_name>: [x, y, z]
games:
  map1:
    world_index: 0
    name: "map test"
    duration_time: 180
    wait_time_before_tp: 10
    max_players_nb: 5
    extraction_areas:
      area1:
        min: [113, 3, -5]
        max: [110, 7, -3]
        wait_time: 10
      area2:
        min: [131, 3, 2]
        max: [134, 7, 5]
        wait_time: 10
    chests:
      medical:
        chest1: [132, 4, -2]
        chest2: [127, 4, -6]
      armor:
        chest1: [127, 4, 2]
        chest2: [123, 4, -2]
      weapons:
        chest1: [119, 4, 0]
        chest2: [118, 4, -7]
      food:
        chest1: [116, 4, 3]
        chest2: [113, 4, -1]
    spawns:
      spawn1: [130, 3, -8]
      spawn2: [130, 3, -4]
      spawn3: [127, 3, -2]
      spawn4: [123, 3, -6]
      spawn5: [123, 3, 1]
      spawn6: [120, 3, 2]
      spawn7: [117, 3, -3]
      spawn8: [114, 3, -7]
      spawn9: [113, 3, 2]
  