#       _                  ____                _ 
#      / \  _   _ _ __ ___|  _ \ _ __ ___   __| |
#     / _ \| | | | '__/ _ \ |_) | '__/ _ \ / _` |
#    / ___ \ |_| | | |  __/  __/| | | (_) | (_| |
#   /_/   \_\__,_|_|  \___|_|   |_|  \___/ \__,_|
# 

name: Tarkox
author: AureProd
main: fr.aureprod.tarkox.Plugin
version: 1.0.0
api-version: 1.16
commands:
  raid:
    description: §6This command is used by players to join or leave a raid.
    usage: "Usage: /raid [join|leave]"
    permission: tarkox.use
    permission-message: §cYou don't have the permission to use this command.
  tarkox-admin:
    description: §6This command is used by admins to manage the plugin for stop and see the status of the raid.
    usage: "Usage: /tarkox-admin [end|status]"
    permission: tarkox.admin
    permission-message: §cYou don't have the permission to use this command.
permissions:
  tarkox.use:
    default: true
    description: §2This permission is used to allow players to use the raid command §4/raid [join|leave]
  tarkox.admin:
    default: op
    description: §2This permission is used to allow players to use the admin command §4/tarkox-admin [end|status]
  